# Generated by Django 2.2.16 on 2022-04-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220404_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
